### ISSUE TITLE
Left/right form for get_rotated_quaternions

### ISSUE THREAD

**Issue by ziotom78** [litebird/ducc#3]
Currently the implementation of `PointingProvider::get_rotated_quaternions` performs a [`rot_ * q`](https://github.com/litebird/ducc/blob/ducc0/python/pointingprovider.cc#L87) multiplication of the `rot` parameter.

Would it be possible to implement the same method for the operation `q * rot_`? This is relevant when converting from the detector's reference frame to a sky reference frame, where you pre-compute the spin-axis-to-sky quaternions once for all and you then call `get_rotated_quaternions` for each detector: in this case, the detector-to-spin-axis quaternion must be on the right side.

**Comment by mreineck** [comment]
Sure, no problem! Would you prefer to have an additional function for this, or should we add a left/right flag to the existing one?

**Comment by ziotom78** [comment]
> Would you prefer to have an additional function for this, or should we add a left/right flag to the existing one?

Thanks! I have no strong preferences, do whatever is more efficient on your side.

**Comment by mreineck** [comment]
#4 should take care of this.

**Comment by ziotom78** [comment]
Awesome, thanks: it works like a charm! Once you merge the PR into `master`, I'll update the dependency in [litebird_sim](https://github.com/litebird/litebird_sim).

**Comment by mreineck** [comment]
Done!
